#!/bin/bash

INGRESO=$2
USUARIO=$1

gdbus call --session \ --dest=org.freedesktop.Notifications \ --object-path=/org/freedesktop/Notifications \ --method=org.freedesktop.Notifications.Notify \ "Markopolo" 0 "" 'Abriendo Youtube' '' \ '[]' '{"urgency": <1>}' 5000

notify-send 'Markopolo' 'Buscando en Youtube'

TARGET=`echo $INGRESO | sed 's/\(^.*videos+de+\|^.*youtube+\)//g'`

firefox --new-tab "https://www.youtube.com/results?search_query=$TARGET" &

aplay `ls ../voice/endwork/* | shuf -n 1`

echo 'Buscando en Youtube...'
