#!/bin/bash

INGRESO="`echo $2 | sed 's/+/ /g' | sed 's/^@//g'`"
USUARIO=$1

echo $USUARIO, no entiendo que quieres decir con \"$INGRESO\"
aplay `ls ../voice/noscript/* | shuf -n 1`
aplay `ls ../voice/repit/* | shuf -n 1`
